### ISSUE TITLE
Missing baselines

### ISSUE THREAD

**Issue by HRSAstro** [tikk3r/maser#4]
Hi, Frits. I have encountered a small issue with extract_taql.py. I have been working with data taken with two different ALMA configurations. When the ms are concatenated, CASA assigns the re-baselined antennas unique names. These two groups of antennas do not have baselines with each other, which causes an error when running the script as it iterates through all the baselines, and when the baseline doesn’t exist the data is assigned None. This would not be an issue for flagged data as these entries would just be zeros but, in my case, the baselines never existed. I got around this by adding a try/except statement in the _for_... loop (line 107). Also, I think line 91 for _corr in range(correlations):_ should be _for corr in range(correlations[0])_, or this causes a Python assignment error.
Cheers,
Hannah

**Comment by tikk3r** [comment]
Hi Hannah (ignore the closing, apparently referencing an issue closes it...).

You're right about line 91, I guess Python handled this correctly internally.

Regarding the missing baselines, I remember this being an issue with the VLA as well and also vaguely something about antenna naming causing problems here if not all of them are present between the two datasets. I've added a small try/except statement that just skips the baseline if it doesn't find it. Let me know if that works.

**Comment by HRSAstro** [comment]
Yes, that's basically the same modification I made. It works fine for me now.
